services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/src/uploads:/app/src/uploads
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    env_file:
      - ./env/server.env
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - "8080:8080"
  db:
    container_name: postgresql
    image: postgres
    env_file:
      - ./env/db.env
    ports:
      - "5431:5432"
    volumes:
      - madashop:/var/lib/postgresql/data

volumes:
  madashop: